apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: "tayssve/hello-go:v4"
        resources:
          requests:
            memory: "25Mi"
            cpu: "50m"
          limits:
            memory: "25Mi"
            cpu: "50m"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000 
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          #initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 1
          # timoutSeconds: 10
          successThreshold: 1
          initialDelaySeconds: 15
        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: goserver-secret
        volumeMounts:
        - name: configmap-volume
          mountPath: /go/myfamily
        - name: goserver-volume
          mountPath: /go/app
      volumes:
      - name: goserver-volume
        persistentVolumeClaim:
          claimName: goserver-pvc
      - name: configmap-volume
        configMap:
          name: configmap-family
          items:
          - key: members
            path: "family.txt"