apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: "tayssve/hello-go:v4"
        envFrom:
        - configMapRef:
            name: goserver-env
        - secretRef:
            name: goserver-secret
            
        volumeMounts:
        - name: configmap-volume
          mountPath: /go/myfamily

      volumes:
      - name: configmap-volume
        configMap:
          name: configmap-family
          items:
          - key: members
            path: "family.txt"