# The command line arguments to run the stress test:
# kubectl run fortio --rm -it --image=fortio/fortio -- load -qps 800 -t 120s -c 70 "http://goserver-service:80/healthz"
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
  minReplicas: 1
  maxReplicas: 30
  targetCPUUtilizationPercentage: 25